// Author: Gust De Wit, r0948039
// For this file, AI was used to help with syntax and structuring, but the core logic and implementation of the polynomial encryption scheme were written by me. The attack was described by me, however, the implementation of the attack was generated by AI based on my description.

PolyKeyGen := function(n, B)
    Zx<x> := PolynomialRing(Integers());
    repeat
        f_coeffs := [Random(-B, B) : i in [1..n]];
        g_coeffs := [Random(-B, B) : i in [1..n]];
        fn := Random(1, B);  // leading coeff nonzero
        gn := Random(1, B);  // leading coeff nonzero
        if Random(1) eq 0 then fn := -fn; end if;
        if Random(1) eq 0 then gn := -gn; end if;
    until GCD(fn, gn) eq 1;
    f := Zx ! (f_coeffs cat [fn]);
    g := Zx ! (g_coeffs cat [gn]);
    return f, g;
end function;

PolyEncrypt := function(m, f, g, U)
    Zx<x> := PolynomialRing(Integers());
    n := Degree(f);
    m_poly := Zx ! m;
    a := Zx ! [Random(-U, U) : i in [1..n]];
    b := Zx ! [Random(-U, U) : i in [1..n]];
    c := a * f + b * g + m_poly;
    return c;
end function;

PolyDecrypt := function(c, f, g)
    n := Degree(f);
    dim := 2 * n;
    
    B := ZeroMatrix(Integers(), dim, dim);
    for i := 0 to n - 1 do
        for j := 0 to n do
            B[i + 1, i + j + 1] := Coefficient(f, j);
        end for;
        for j := 0 to n do
            B[n + i + 1, i + j + 1] := Coefficient(g, j);
        end for;
    end for;
    
    L := Lattice(B);
    
    target := Vector(Integers(), dim, [Coefficient(c, i) : i in [0..dim-1]]);
    
    closest := ClosestVectors(L, target);
    lattice_point := closest[1];

    m_vec := target - lattice_point;
    m := [Integers() ! m_vec[i] : i in [1..n]];
    
    return m;
end function;

PolyPlaintextAttack := function(cs, ps, n, B, U)
    Zx := Parent(cs[1]);
    
    ds := [cs[i] - ps[i] : i in [1..#cs]];
    num := #ds;

    // Step 1: Find combinations of d_i that have degree <= n
    lambda := 10^6;
    
    M := ZeroMatrix(Integers(), num, num + n - 1);
    for i := 1 to num do
        M[i, i] := 1;
        for j := 1 to n - 1 do
            M[i, num + j] := lambda * Coefficient(ds[i], n + j);
        end for;
    end for;
    
    L := Lattice(M);
    Lred := LLL(L);
    Bred := BasisMatrix(Lred);
    
    // Select only degree <= n columns
    deg_n_polys := [];
    for i := 1 to Nrows(Bred) do
        top_cols := [Bred[i, j] : j in [num+1..num+n-1]];
        if top_cols ne [0 : k in [1..n-1]] then continue; end if;
        
        combo := [Bred[i, j] : j in [1..num]];
        poly := Zx ! 0;
        for j := 1 to num do
            poly := poly + combo[j] * ds[j];
        end for;
        
        if Degree(poly) ge 1 then
            Append(~deg_n_polys, poly);
        end if;
    end for;
    
    // Step 2: Build second lattice from their coefficients and LLL-reduce
    num2 := #deg_n_polys;
    M2 := ZeroMatrix(Integers(), num2, n + 1);
    for i := 1 to num2 do
        for j := 0 to n do
            M2[i, j + 1] := Coefficient(deg_n_polys[i], j);
        end for;
    end for;
    
    L2 := Lattice(M2);
    L2red := LLL(L2);
    B2red := BasisMatrix(L2red);
    
    // The shortest vectors should be f and g
    candidates := [];
    for i := 1 to Nrows(B2red) do
        row := [B2red[i, j] : j in [1..n+1]];
        poly := Zx ! row;
        if Degree(poly) eq n and Max([Abs(c) : c in row]) le B then
            Append(~candidates, poly);
        end if;
    end for;
    
    if #candidates ge 2 then
        for i := 1 to #candidates do
            for j := i+1 to #candidates do
                if GCD(LeadingCoefficient(candidates[i]),
                       LeadingCoefficient(candidates[j])) eq 1 then
                    return candidates[i], candidates[j];
                end if;
            end for;
        end for;
        return candidates[1], candidates[2];
    end if;
    
    error "Attack failed: not enough candidates";
end function;

// AI was used to generate the following test code for the attack:
TestAttackMultiple := procedure(n, B, U, num_pairs, trials)
    printf "Testing n=%o, B=%o, U=%o, pairs=%o: ", n, B, U, num_pairs;
    success := 0;
    for t := 1 to trials do
        f, g := PolyKeyGen(n, B);
        Zx := Parent(f);
        cs := [];
        ps := [];
        for i := 1 to num_pairs do
            msg := [Random(0, 1) : j in [1..n]];
            m_poly := Zx ! msg;
            c := PolyEncrypt(msg, f, g, U);
            Append(~cs, c);
            Append(~ps, m_poly);
        end for;
        try
            f_rec, g_rec := PolyPlaintextAttack(cs, ps, n, B, U);
            msg_test := [Random(0, 1) : j in [1..n]];
            c_test := PolyEncrypt(msg_test, f, g, U);
            m_dec := PolyDecrypt(c_test, f_rec, g_rec);
            if m_dec eq msg_test then
                success +:= 1;
            end if;
            if (f_rec eq f or f_rec eq -f or f_rec eq g or f_rec eq -g) and
            (g_rec eq f or g_rec eq -f or g_rec eq g or g_rec eq -g) then
                printf "Keys match up to sign/swap\n";
            elif f_rec ne f or g_rec ne g then
                printf "Recovered keys do not match original keys\n";
            end if;;
        catch e
            ; // attack failed
        end try;
    end for;
    printf "%o/%o\n", success, trials;
end procedure;

TestAttackMultiple(16, 5, 100, 40, 5);
TestAttackMultiple(24, 5, 100, 60, 5);
TestAttackMultiple(32, 5, 100, 80, 5);
TestAttackMultiple(48, 5, 100, 120, 5);
TestAttackMultiple(64, 5, 100, 160, 5);